version: "3.3"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: brandondev
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: my_store
    container_name: my_store_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    container_name: pgadmin
    ports:
      - "5050:80"
